### ISSUE TITLE
Error when trying to marshal a self-defined class

### ISSUE THREAD

**Issue by asfluido** [mruby/mgem-list#251]
Example code:

```ruby
class C
  def initialize(o)
    @o=o
  end
end

Marshal::dump(C::new(1))
```
Raises an exception pointing to marshal.cpp:27 - lhs is zero. Sadly this gem is written in C++ and I cannot help in debugging...

gdb stack:

```
#0  0x00000000004bc2ee in operator!= (lhs=..., sym=5307) at /home/dvl/motri/mruby/build/mrbgems/mruby-marshal/src/marshal.cpp:27
#1  0x00000000004bc6fe in (anonymous namespace)::write_context::symbol (this=0x7ffdd62c47f0, sym=5307) at /home/dvl/motri/mruby/build/mrbgems/mruby-marshal/src/marshal.cpp:101
#2  0x00000000004bcba5 in (anonymous namespace)::write_context::class_symbol (this=0x7ffdd62c47f0, v=0x2e18ee0) at /home/dvl/motri/mruby/build/mrbgems/mruby-marshal/src/marshal.cpp:164
#3  0x00000000004bffc6 in (anonymous namespace)::write_context::klass<(char)'o'> (this=0x7ffdd62c47f0, v=..., check=true) at /home/dvl/motri/mruby/build/mrbgems/mruby-marshal/src/marshal.cpp:191
#4  0x00000000004bd439 in (anonymous namespace)::write_context::marshal (this=0x7ffdd62c47f0, v=..., limit=-2) at /home/dvl/motri/mruby/build/mrbgems/mruby-marshal/src/marshal.cpp:252
#5  0x00000000004bf7b7 in (anonymous namespace)::marshal_dump (M=0x2a7f3c0) at /home/dvl/motri/mruby/build/mrbgems/mruby-marshal/src/marshal.cpp:678
#6  0x000000000046ddc8 in mrb_vm_exec (mrb=0x2a7f3c0, proc=0x2e18f10, pc=0x2e432d0) at /home/dvl/motri/mruby/src/vm.c:1325
#7  0x000000000046c01a in mrb_vm_run (mrb=0x2a7f3c0, proc=0x2e18f10, self=..., stack_keep=5) at /home/dvl/motri/mruby/src/vm.c:861
#8  0x000000000047489b in mrb_top_run (mrb=0x2a7f3c0, proc=0x2e18f10, self=..., stack_keep=0) at /home/dvl/motri/mruby/src/vm.c:2748
#9  0x0000000000485da0 in mrb_load_exec (mrb=0x2a7f3c0, p=0x2e365e0, c=0x2e36400) at /home/dvl/motri/mruby/mrbgems/mruby-compiler/core/parse.y:5780
#10 0x0000000000485e16 in mrb_load_file_cxt (mrb=0x2a7f3c0, f=0x2e361b0, c=0x2e36400) at /home/dvl/motri/mruby/mrbgems/mruby-compiler/core/parse.y:5789
#11 0x0000000000446788 in main (argc=2, argv=0x7ffdd62c5398) at /home/dvl/motri/mruby/mrbgems/mruby-bin-mruby/tools/mruby/mruby.c:227
```

**Comment by asfluido** [comment]
Problem disappeared with latest mruby. Still, this C++ presence is so frustrating...

**Comment by take-cheeze** [comment]
At least this is not the place to post bug report.
Feel free to post a bug report to my repository: https://github.com/take-cheeze/mruby-marshal/issues

**Comment by asfluido** [comment]
Subject: Re: [mruby/mgem-list] Error when trying to marshal a self-defined class (#251)
	Date: mer 11 ott 17 10:22:34 +0000

Quoting Takeshi Watanabe (notifications@github.com):

>    At least this is not the place to post bug report.
>    Feel free to post a bug report to my repository:
>    [1]https://github.com/take-cheeze/mruby-marshal/issues

Oh.. I see. My mistake - I thought I was on your gem's page.

Carlo

-- 
  *         Se la Strada e la sua Virtu' non fossero state messe da parte,
* K * Carlo E. Prelz - fluido@fluido.as             che bisogno ci sarebbe
  *               di parlare tanto di amore e di rettitudine? (Chuang-Tzu)
